data:
  data: cora
  dir: './data'
  nfeat: 1433
  nlabel: 7

diffusion:
  method: Gaussian
  step: 80
  s: 0.008

model:
  model: GCNConv
  nhid: 16
  cat_mode: False
  skip: False
  num_layers: 2
  num_linears: 2

train:
  num_epochs: 20000
  save_interval: 1000
  print_interval: 100
  time_batch: 16
  lr: 0.003
  lr_schedule: True
  weight_decay: 0.003
  lr_decay: 0.9999999
  eps: 1.0e-5
  unweighted_MSE: False
