data:
  data: dblp
  dir: './data'
  nfeat: 100
  nlabel: 3

diffusion:
  method: Gaussian
  step: 40
  s: 0.008

model:
  model: GCNConv
  nhid: 16
  cat_mode: False
  skip: False
  num_layers: 2
  num_linears: 2

train:
  num_epochs: 30000
  print_interval: 100
  time_batch: 16
  lr: 0.005
  lr_schedule: True
  weight_decay: 0
  lr_decay: 0.9999999
  eps: 1.0e-5
  unweighted_MSE: False
  grad_norm: 0.1
