data:
  data: pubmed
  dir: './data'
  nfeat: 500
  nlabel: 3

diffusion:
  method: Gaussian
  step: 80
  s: 0.008

model:
  model: GCNConv
  nhid: 16
  cat_mode: False
  skip: False
  num_layers: 2
  num_linears: 2

train:
  num_epochs: 10000
  print_interval: 200
  time_batch: 16
  lr: 0.0005
  lr_schedule: True
  weight_decay: 0.003
  lr_decay: 0.9999999
  eps: 1.0e-5
  unweighted_MSE: True
